= Include Content by Tagged Regions
// aka Select Portions of a Document to Include

The include directive enables you to select portions of a file to include instead of including the whole file.
Use the `lines` attribute to include individual lines or a range of lines (by line number).
Use the `tags` attribute (or `tag` attribute for the singular case) to select lines that fall between regions marked with user-defined tags.

When including multiple line ranges or multiple tags, each entry in the list must be separated by either a comma or a semi-colon.
If commas are used, the entire value must be enclosed in quotes.
You can eliminate this requirement by using the semi-colon as the data separator instead.

== Tagging regions

Tags are useful when you want to identify specific regions of a file to include.
You can then select the lines between the boundaries of the include tag/end directives to include using the `tags` attribute.

Including by tag includes all regions marked with that tag.
This makes it possible to include a group of lines from different regions of the document using a single tag.

TIP: If the target file has tagged lines, and you just want to ignore those lines, use the `tags` attribute to filter them out.
See <<tag-filtering>> for details.

The example below shows how you tag a region of content inside a file containing multiple code examples.

.Tagged code snippets in a file named core.rb
[source,ruby,subs=attributes+]
----
include::example$include.adoc[tag=tag-co]
----
<.> To indicate the start of a tagged region, insert a comment line in the code.
<.> Assign a name to the `tag` directive. In this example, the tag is named _timings_.
<.> Insert another comment line where you want the tagged region to end.
<.> Assign the name of the region you want to terminate to the `end` directive.
<.> This is the start of a tagged snippet named _parse_.
<.> This is the end of the tagged snippet named _parse_.

IMPORTANT: The `tag::[]` and `end::[]` directives should be placed after a line comment as defined by the language of the source file.
The directives must also appear at the _end_ of the line.
In the previous example, we choose to prefix the lines with a hash (`#`) because that's the start of a line comment in Ruby.

TIP: For languages that only have circumfix comments, such as XML, you can enclose the tag and end directives in the respective circumfix comment markers.
For example, in XML files, you can use `+<!-- tag::name[] -->+` and `+<!-- end::name[] -->+` (the spaces around the tag are required).

In the next example, the tagged region named _parse_ is selected by the `include` directive.

.Selecting the _parse_ code snippet from a document
[source]
....
include::example$include.adoc[tag=target-co]
....
<.> In the directive's brackets, set the `tag` attribute and assign it the unique name of the code snippet you tagged in your code file.

You can include multiple tags from the same file.

.Selecting the _timings_ and the _parse_ code snippets from a document
[source]
....
include::example$include.adoc[tag=target-co-multiple]
....

It is also possible to have fine-grained tagged regions inside larger tagged regions.

For example, if your include file has the following content:

----
// tag::snippets[]
// tag::snippet-a[]
snippet a
// end::snippet-a[]

// tag::snippet-b[]
snippet b
// end::snippet-b[]
// end::snippets[]
----

And you include this file using the following include directive:

----
\include::file-with-snippets.adoc[tag=snippets]
----

The following lines will be selected and displayed:

....
snippet a

snippet b
....

Notice that none of the lines with the tag directives are displayed.

[#tag-filtering]
== Tag filtering

The previous section showed how to select tagged regions explicitly, but you can also use wildcards and exclusions.
These expressions give you the ability to include or exclude tags in bulk.
For example, here's how to include all lines that are not enclosed in a tag:

----
\include::file-with-snippets.adoc[tag=!*]
----

When tag filtering is used, lines that contain a tag directive _are always discarded_ (like a line comment).
Even if you're not including content by tags, you can specify the double wildcard (`+**+`) to filter out all lines in the include file that contain a tag directive.

The modifiers you can use for filtering are as follows:

`*`::
The single wildcard.
Select all tagged regions.
May only be specified once, negated or not.

`**`::
The double wildcard.
Select all the lines in the document *except for lines that contain a tag directive*.
Use this symbol if you want to include a file that has tag directives, but you want to discard the lines that contain a tag directive.
May only be specified once, negated or not.

`!`::
Negate the wildcard or tag.

The double wildcard is always applied first, regardless of where it appears in the list.
If the double wildcard is not negated (i.e., `+**+`), it should only be combined with exclusions (e.g., `+**;!foo+`).
A negated double wildcard (i.e., `+!**+`), which selects no lines, is usually implied as the starting point.
A negated single wildcard has different meaning depending on whether it comes before tag names (e.g., `+!*;foo+`) or after at least one tag name (e.g., `+foo;!*+`).

Let's assume we have a region tagged `foo` with a nested region tagged `bar`.
Here are some of the permutations you can use (along with their implied long-hand forms):

`+**+`:: Selects all the lines in the document (except for lines that contain a tag directive).
_(implies `+**;*+`)_

`+*+`:: Selects all tagged regions in the document.
Does not select lines outside of tagged regions.
_(implies `+!**;*+`)_

`+!*+`:: Selects only the regions in the document outside of tags (i.e., non-tagged regions).
_(implies `+**;!*+`)_

`foo`:: Selects only regions tagged _foo_.
_(implies `+!**;foo+`)_

`foo;!bar`:: Selects only regions tagged _foo_, but excludes any nested regions tagged _bar_.
_(implies `+!**;foo;!bar+`)_

`+foo;!*+`:: Selects only regions tagged _foo_, but excludes any nested tagged regions.
_(implies `+!**;foo;!*+`)_

`+*;!foo+`:: Selects all tagged regions, but excludes any regions tagged _foo_ (nested or otherwise).
_(implies `+!**;*;!foo+`)_

`!foo`:: Selects all the lines in the document except for regions tagged _foo_.
_(implies `+**;!foo+`)_

`!foo;!bar`:: Selects all the lines in the document except for regions tagged _foo_ or _bar_.
_(implies `+**;!foo;!bar+`)_

`+!*;foo+`:: Selects the regions in the document outside of tags (i.e., non-tagged regions) and inside regions tagged _foo_, excluding any nested tagged regions.
To include nested tagged regions, they each must be named explicitly.
_(implies `+**;!*;foo+`)_

If the filter begins with a negated tag or single wildcard, it implies that the pattern begins with `+**+`.
An exclusion not preceded by an inclusion implicitly starts by selecting all the lines that do not contain a tag directive.
Otherwise, it implies that the pattern begins with `+!**+`.
A leading inclusion implicitly starts by selecting no lines.
