= Font-Based Icons
:url-fontawesome-icons: https://fontawesome.com/icons?d=gallery

Asciidoctor can use the Font Awesome icon set.
You can see the available icons and their names on the {url-fontawesome-icons}[Font Awesome icons page^].
Using the Font Awesome icons requires online access by default.

IMPORTANT: The default CSS stylesheet is required when using font-based icons.

== Use the Font Awesome icons

To use Font Awesome's icons in your document, set the value of the `icons` document attribute to `font` in the document header.

[source]
----
= Document Title
:icons: font <.>

icon:tags[] ruby, asciidoctor <.>
----
<.> Set `icons` to `font` to use the Font Awesome icons.
<.> Enter the name of the Font Awesome icon in the target field of the inline icon macro, followed by a set of square brackets (`[]`).

.Result: Use Font Awesome tags icon
icon:tags[] ruby, asciidoctor

When font-based icons are activated, Asciidoctor adds a reference to the Font Awesome stylesheet and font files served from a CDN to the document header:

[source,xml]
----
<link rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
----

Here's how the HTML converter converts the above syntax when the `icons` attribute is assigned the `font` value.

.Result: HTML output
[source,xml]
----
<div class="paragraph">
<p><span class="icon"><i class="fa fa-tags"></i></span> ruby, asciidoctor</p>
</div>
----

== Icon macro attributes for Font Awesome icons

The icon macro has a few attributes that modify the size and orientation of a Font Awesome icon.
These attributes are specific to Font Awesome and only apply to the HTML output when `icons` is assigned the `font` value.

`size`::
First positional attribute; scales the icon; values: `1x` (default), `2x`, `3x`, `4x`, `5x`, `lg`, `fw`

`rotate`::
Rotates the icon; values: `90`, `180`, `270`

`flip`::
Flips the icon; values: `horizontal`, `vertical`

=== Change the size of an icon

The first unnamed positional attribute is `size`.
For instance, to make the icon twice the size as the default, enter `2x` inside the square brackets.

[source]
----
icon:heart[2x]
----

This is equivalent to:

[source]
----
icon:heart[size=2x]
----

And this is how icon:heart[size=2x] displays.

The previous example emits the following HTML:

[source,html]
----
<span class="icon"><i class="fa fa-heart fa-2x"></i></span>
----

[TIP]
====
If you want to line up icons so that you can use them as bullets in a list, use the `fw` size as follows:

----
[%hardbreaks]
icon:bolt[fw] bolt
icon:heart[fw] heart
----
====

=== Rotate and flip an icon

To rotate and flip an icon, specify these options using named attributes:

[source]
----
icon:shield[rotate=90, flip=vertical]
----

The icon icon:shield[rotate=90, flip=vertical] is rotated 90{deg} and flipped vertically.

////
The previous example emits the following HTML:

[source,xml]
----
<span class="icon"><i class="fa-shield fa-rotate-90 fa-flip-vertical"></i></span>
----
////

== Link and window attributes

It's possible to add additional metadata to an inline icon.
The `link` and `window` attributes apply to both font-based and image-based icons.

`link`::
The URI target used for the icon, which will wrap the converted icon in a link

`window`::
The target window of the link (when the `link` attribute is specified) (HTML converter)

Here's an example of an icon with a link:

[source]
----
icon:download[link="https://rubygems.org/downloads/asciidoctor-2.0.10.gem"]
----

The previous example emits the following HTML:

[source,html]
----
<span class="icon"><a class="image" href="https://rubygems.org/downloads/asciidoctor-2.0.10.gem"><i class="fa-download"></i></a></span>
----

== Default font-based admonition icons

When font-based icons are enabled, Asciidoctor will draw the icons for the 5 built-in admonition types using Font Awesome.
To use the default font-based admonition icons for admonitions, set the value of the `icons` document attribute to `font` in the document header.

[source]
----
= Document Title
:icons: font

NOTE: Asciidoctor supports font-based admonition icons, powered by Font Awesome!
----

// We need to explain that the default admonition icons have different names (i.e., `icon-note` instead of `fa-note`, because they're built in to the stylesheet.

Asciidoctor will emit HTML markup that selects the appropriate font character from the Font Awesome font for each admonition block.
For instance, Asciidoctor selects the Font Awesome icon `icon-note` for `NOTE` admonition blocks.

.Result: HTML output when the icons attribute is set to font
[source,html]
----
<div class="admonitionblock note">
<table>
<tr>
<td class="icon">
<i class="fa icon-note" title="Note"></i>
</td>
<td class="content">
Asciidoctor supports font-based admonition icons, powered by Font Awesome!
</td>
</tr>
</table>
</div>
----

This is how the admonition looks rendered.

NOTE: Asciidoctor supports font-based admonition icons, powered by Font Awesome!

The icons chosen are selected by the stylesheet.
The default stylesheet maps icons to the following 5 CSS classes:

* .admonitionblock td.icon .icon-note
* .admonitionblock td.icon .icon-tip
* .admonitionblock td.icon .icon-warning
* .admonitionblock td.icon .icon-caution
* .admonitionblock td.icon .icon-important

If you want to customize the icon or the color that is used, you'll need to provide a custom stylesheet or override the styles using a docinfo file.
Here's an example that shows how to change the icon for the note admonition to sticky note:

[source,css]
----
.admonitionblock td.icon .icon-note::before {
  content: "\f24a";
  color:black;
}
----
