= AsciiDoc Language User Documentation
:url-org: https://github.com/asciidoctor
:url-asciidoc-lang: https://gitlab.eclipse.org/eclipse/asciidoc-lang/asciidoc-lang
:url-docs: https://docs.asciidoctor.org/asciidoc/latest

**This repository is now archived.**

This repository provided the source of the initial contribution for the {url-asciidoc-lang}[AsciiDoc Language(TM) project at Eclipse].
That contribution consisted of the user documentation for the AsciiDoc(R) language as interpreted by {url-org}/asciidoctor[Asciidoctor]. 
It was contributed by the Asciidoctor project.
The user documentation now resides in the [.path]_docs_ folder of the {url-asciidoc-lang}[repository] for the AsciiDoc Language project.

The Asciidoctor project will continue to host a copy of the AsciiDoc user documentation.
You can view the published version of the user documentation {url-docs}[online].

== Copyright and License

Copyright (C) 2012-present Sarah White, Dan Allen, and the individual contributors to {url-org}/asciidoctor/graphs/contributors[Asciidoctor] and {url-org}/asciidoctor.org/graphs/contributors[asciidoctor.org].
Except where otherwise noted, the content of the AsciiDoc documentation and websites is licensed under a https://creativecommons.org/licenses/by/4.0/[Creative Commons Attribution 4.0 International License].
The use of the {url-org}[Asciidoctor projects] is granted under the terms of each software project's license.

== Authors

*Asciidoctor* is led by https://github.com/mojavelinux[Dan Allen] and https://github.com/graphitefriction[Sarah White] and has received contributions from many individuals in Asciidoctor's awesome community.
The project was initiated in 2012 by https://github.com/erebor[Ryan Waldron] and based on a prototype written by https://github.com/nickh[Nick Hengeveld].

*AsciiDoc* was started and maintained by Stuart Rackham from https://github.com/asciidoc/asciidoc/blob/master/CHANGELOG.txt[2002 to 2013] and has received contributions from many individuals in the https://github.com/asciidoc/asciidoc/graphs/contributors[AsciiDoc community].

The user documentation for the AsciiDoc language was extracted from the tip of the https://github.com/asciidoctor/asciidoctor.org/tree/docs-archive[docs-archive branch] in the https://github.com/asciidoctor/asciidoctor.org repository, imported into this repository, revised for accuracy, and contributed by the Asciidoctor project.

== Trademarks

AsciiDoc(R) and AsciiDoc Language(TM) are trademarks of the Eclipse Foundation, Inc.
