= Collapsible Blocks

You can designate block content to be revealed or hidden on interaction using the collapsible option and its companion, the open option.
When the AsciiDoc source is converted to HTML, this block gets mapped to a disclosure summary element (i.e., a summary/details pair).
If the output format does not support this interaction, it may be rendered as an unstyled block (akin to an open block).

== Collapsible block syntax

You make block content collapsible by specifying the `collapsible` option on the example structural container.
This option changes the block from an example block to a collapsible block.

.Collapsible block syntax
[#ex-collapsible]
----
include::example$collapsible.adoc[tag=basic]
----

In the output, the content of this block is hidden until the reader clicks the default title, "`Details`".
The result of <<ex-collapsible>> is displayed below.

include::example$collapsible.adoc[tag=basic]

Like other blocks, the collapsible block recognizes the `id` and `role` attributes.

== Collapsible paragraph syntax

If the content of the block is only a single paragraph, you can use the example paragraph style instead of the example structural container to make a collapsible paragraph.

.Collapsible paragraph syntax
[#ex-collapsible-paragraph]
----
include::example$collapsible.adoc[tag=paragraph]
----

In the output, the content of this block is hidden until the reader clicks the default title, "`Details`".
The result of <<ex-collapsible-paragraph>> is displayed below.

include::example$collapsible.adoc[tag=paragraph]

== Customize the toggle text

If you want to customize the text that toggles the display of the collapsible content, specify a title on the block or paragraph.

.Collapsible block with custom title
[#ex-collapsible-with-title]
----
include::example$collapsible.adoc[tag=title]
----

The result of <<ex-collapsible-with-title>> is displayed below.

include::example$collapsible.adoc[tag=title]

Notice that even though this block has a title, it's not numbered and does not have a caption prefix.
That's because it's not an example block and thus does not get a numbered caption prefix like an example block would.

== Default to open

If you want the collapsible block to be open by default, specify the `open` option as well.

.Collapsible block that defaults to open
[#ex-collapsible-open]
----
include::example$collapsible.adoc[tag=open]
----

The result of <<ex-collapsible-open>> is displayed below.

include::example$collapsible.adoc[tag=open]

== Use as an enclosure

Much like the open block, the collapsible block is an enclosure.
If you want to make other types of blocks collapsible, such as an listing block, you can nest the block inside the collapsible block.

.Collapsible block that encloses a literal block
[#ex-collapsible-nested]
----
include::example$collapsible.adoc[tag=nested]
----

The result of <<ex-collapsible-nested>> is displayed below.

include::example$collapsible.adoc[tag=nested]

Since the toggle text acts as the block title, you may decide to not put a title on the nested block, as in this example.
