= Header Overview

The document header is a set of contiguous lines at the start of the document that encapsulates the document title, author and revision information, metadata, and document-wide attributes.

== Document header structure

The document header is a set of contiguous lines that starts on the first line of the file.

WARNING: The document header can't contain blank lines or block content.
The first blank line that the processor encounters is interpreted as the end of the document header and the beginning of the document body.

A header typically begins with a xref:title.adoc[].
When a document title is specified, it can be immediately followed by two special (but optional) lines of content that assign xref:author-information.adoc[] and xref:revision-information.adoc[].

Additionally, the header can contain the following elements as long as there aren't any blank lines between any of the entries:

* optional document-wide attributes (built-in and user-defined) that are declared using xref:attributes:attribute-entries.adoc[attribute entries],
* optional xref:metadata.adoc[metadata], such as a description or keywords, and
* optional xref:ROOT:comment.adoc#comment-lines[comment lines].

Notice in <<ex-basic-header>> that there are no blank lines between any of the entries; the lines are contiguous.

.Common elements in a header
[source#ex-basic-header]
----
= Document Title <.>
Kismet R. Lee <kismet@asciidoctor.org> <.>
:description: The document's description. <.>
:sectanchors: <.>
:url-repo: https://my-git-repo.com <.>
<.>
----
<.> Document title
<.> Author line
<.> Attribute entry assigning metadata to a built-in document attribute
<.> Attribute entry setting a built-in document attribute
<.> Attribute entry assigning a value to a user-defined document attribute
<.> Blank line that ends the document header

There are a few attribute entries in <<ex-basic-header>>.
Each attribute entry, whether built-in or user-defined, must be entered on its own line.
While attribute entries can be placed anywhere in the header, including above the document title, the preferred placement is below the title, if it's present.
Since the document title is optional, it's possible for the header to only consist of attribute entries.

== When does the document header end?

*The first blank line in the document marks the end of the header.*
The next line after the first blank line that contains content is interpreted as the beginning of the document's body.

.Terminating a document header
[source#ex-terminate]
----
= Document Title
Kismet R. Lee <kismet@asciidoctor.org>
:url-repo: https://my-git-repo.com
<.>
This is the first line of content in the document body. <.>
----
<.> A blank line ends the document header.
<.> After the blank line, the next line with content starts the body of the document.

The first line of the document body can be any valid AsciiDoc content, such as a section heading, paragraph, table, include directive, image, etc.
Any attributes defined below the first blank line are not part of the document header and will not be scoped to the entire document.

== Header requirements per doctype

The header is optional when the `doctype` is `article` or `book`.
A header is required when the document type is `manpage`.
See the xref:asciidoctor:backends:manpage/convert-to-man-page.adoc#man-page-doctype[man page doctype] section for manual page (man page) requirements.

== Header processing

The information in the document header is included by default when converting to a standalone document.
This means that the header of a document called via an xref:directives:include.adoc[include directive] will be processed and converted.
If you don't want the header of a document to be displayed, set the `noheader` attribute in the document's header or via the CLI.

== Front matter

Many static site generators, such as Jekyll and Middleman, rely on front matter added to the top of the document to determine how to convert the content.
Asciidoctor has a number of attributes available to correctly handle front matter.
See xref:asciidoctor:backends:html/front-matter.adoc[] to learn more.
