= Ordered Lists
:keywords: numbered list

== Basic ordered list

Sometimes, we need to number the items in a list.
Instinct might tell you to prefix each item with a number, like in this next list:

----
include::example$ordered.adoc[tag=base-num]
----

The above works, but since the numbering is obvious, the AsciiDoc processor will insert the numbers for you if you omit them:

----
include::example$ordered.adoc[tag=base]
----

====
include::example$ordered.adoc[tag=base]
====

If you decide to manually number your ordered list, you have to keep them sequential.
This differs from other lightweight markup languages.
It's one way to adjust the numbering offset of a list.
For instance, you can type:

----
include::example$ordered.adoc[tag=base-num-start]
----

However, in general the best practice is to use the `start` attribute to configure this sort of thing:

----
include::example$ordered.adoc[tag=base-start]
----

.When not to use the start attribute
****
When an ordered list item contains block content--such as an image, source block, or table--you may observe that the number of the next item in the list resets to 1.
In fact, what's happened is that a new list has been started where the number resets due to a missing list continuation.

In these cases, you should not resort to using the `start` attribute to fix the numbering.
Not only does that require manual adjustment as items are added to the list, it doesn't address the underlying semantics problem, which is what is causing it to be broken.
Instead, use a list continuation between each block element you want to attach to the list item to ensure the list item is continuous.
The list continuation glues the blocks together within a given item and keeps them at the same level of indentation.

* For details on how to use a list continuation, refer to the xref:continuation.adoc[] page.
* For an example of the list continuation used in a complex ordered list, see the launch steps in https://github.com/aws-quickstart/quickstart-microsoft-sql-fci-fsx/blob/main/docs/partner_editable/deploy_steps.adoc[this .adoc file in GitHub^].
* To see how those launch steps look in the final output, see the https://aws-quickstart.github.io/quickstart-microsoft-sql-fci-fsx/#_launch_the_quick_start[Launch the Quick Start^] section of the generated deployment guide.
The list continuations prevent step 2 from resetting to 1.
They also prevent step 5, which is pulled in from a separate AsciiDoc file, from resetting to 1.
****

To present list items in reverse order, add the `reversed` option:

----
include::example$ordered.adoc[tag=reversed]
----

====
include::example$ordered.adoc[tag=reversed]
====

You can give a list a title by prefixing the line with a dot immediately followed by the text (without leaving any space after the dot).

Here's an example of a list with a title:

----
include::example$ordered.adoc[tag=base-t]
----

====
include::example$ordered.adoc[tag=base-t]
====

== Nested ordered list

// tag::basic[]
You create a nested item by using one or more dots in front of each the item.

----
include::example$ordered.adoc[tag=nest]
----

AsciiDoc selects a different number scheme for each level of nesting.
Here's how the previous list renders:

.A nested ordered list
====
include::example$ordered.adoc[tag=nest]
====
// end::basic[]

[TIP]
====
Like with the asterisks in an unordered list, the number of dots in an ordered list doesn't represent the nesting level.
However, it's much more intuitive to follow this convention:

*# of dots = level of nesting*

Again, we are shooting for plain text markup that is readable _as is_.
====

You can mix and match the three list types, ordered, xref:unordered.adoc[unordered], and xref:description.adoc[description], within a single hybrid list.
The AsciiDoc syntax tries hard to infer the relationships between the items that are most intuitive to us humans.

Here's an example of nesting an unordered list inside of an ordered list:

----
include::example$ordered.adoc[tag=mix]
----

====
include::example$ordered.adoc[tag=mix]
====

You can spread the items out and indent the nested lists if that makes it more readable for you:

----
include::example$ordered.adoc[tag=mix-alt]
----

The description list page demonstrates how to xref:description.adoc#three-hybrid[combine all three list types].

[#styles]
== Number styles

For ordered lists, AsciiDoc supports the numeration styles such as lowergreek and decimal-leading-zero.
The full list of numeration styles that can be applied to an ordered list are as follows:

[%autowidth]
|===
|Block style |CSS list-style-type

|arabic
|decimal

|decimal ^[1]^
|decimal-leading-zero

|loweralpha
|lower-alpha

|upperalpha
|upper-alpha

|lowerroman
|lower-roman

|upperroman
|upper-roman

|lowergreek ^[1]^
|lower-greek
|===
^[1]^ These styles are only supported by the HTML converters.

Here are a few examples showing various numeration styles as defined by the block style shown in the header row:

[%autowidth]
|===
|[arabic] ^[2]^ |[decimal] |[loweralpha] |[lowergreek]

a|
. one
. two
. three

a|
[decimal]
. one
. two
. three

a|
[loweralpha]
. one
. two
. three

a|
[lowergreek]
. one
. two
. three
|===
^[2]^ Default numeration if block style is not specified

TIP: Custom numeration styles can be implemented using a custom role.
Define a new class selector (e.g., `.custom`) in your stylesheet that sets the `list-style-type` property to the value of your choice.
Then, assign the name of that class as a role on any list to which you want that numeration applied.

When the role shorthand (`.custom`) is used on an ordered list, the numeration style is no longer omitted.

You can override the number scheme for any level by setting its style (the first positional entry in a block attribute list).
You can also set the starting number using the `start` attribute:

----
include::example$ordered.adoc[tag=num]
----

====
include::example$ordered.adoc[tag=num]
====

IMPORTANT: The `start` attribute must be a number, even when using a different numeration style.
For instance, to start an alphabetic list at letter "c", set the numeration style to loweralpha and the start attribute to 3.
