= Unordered Lists
:keywords: bulleted list

If you were to create a list in an e-mail, how would you do it?
Chances are, you'd mark list items using the same characters that AsciiDoc reserves to identify list items.

== Basic unordered list

In the example below, each list item is marked using an asterisk (`+*+`), the AsciiDoc syntax specifying an unordered list item.

----
include::example$unordered.adoc[tag=base]
----

A list item's first line of text must be offset from the marker (`+*+`) by at least one space.
If you prefer, you can indent list items.
Empty lines are required before and after a list.
Additionally, empty lines are permitted, but not required, between list items.

.Rendered unordered list
====
include::example$unordered.adoc[tag=base]
====

You can add a title to a list by prefixing the title with a period (`.`).

----
include::example$unordered.adoc[tag=base-t]
----

.Rendered unordered list with a title
====
include::example$unordered.adoc[tag=base-t]
====

Was your instinct to use a hyphen (`-`) instead of an asterisk to mark list items?
Guess what?
That works too!

----
include::example$unordered.adoc[tag=base-alt]
----

You should reserve the hyphen for lists that only have a single level because the hyphen marker (`-`) doesn't work for nested lists.
Now that we've mentioned nested lists, let's go to the next section and learn how to create lists with multiple levels.

[#separating-lists]
.Forcing lists apart
****
If you have adjacent lists, they have the tendency to want to fuse together.
To force lists apart, insert a line comment (`//`) surrounded by empty lines between the two lists.
Here's an example, where the `-` text in the line comment indicates the line serves as an "`end of list`" marker:

----
include::example$unordered.adoc[tag=divide]
----

This technique works for all list types.
See xref:separating.adoc[] for more details.
****

== Nested unordered list

To nest an item, just add another asterisk (`+*+`) to the marker.
Continue doing this for each subsequent level.

----
include::example$unordered.adoc[tag=nest]
----

.Rendered nested, unordered list
====
include::example$unordered.adoc[tag=nest]
====

You can nest unordered lists to any depth.
Keep in mind, however, that some interfaces will begin flattening lists after a certain depth.
For instance, GitHub starts flattening list after 10 levels of nesting.

----
include::example$unordered.adoc[tag=max]
----

====
include::example$unordered.adoc[tag=max]
====

While it would seem as though the number of asterisks represents the nesting level, that's not how depth is determined.
A new level is created for each unique marker encountered.
For example, you can create a second level using the hyphen marker instead of two asterisks.

.Using hyphen to mark the second level is not recommended
----
include::example$unordered.adoc[tag=nest-alt]
----

However, it's much more intuitive to follow the convention that the marker length (i.e., number of asterisks) equals the level of nesting.
The hyphen should only be used as the marker for the first level.

*marker length = level of nesting*

After all, we're shooting for plain text markup that is readable _as is_.

[#markers]
== Custom markers

AsciiDoc offers numerous bullet styles for lists.
The list marker (bullet) is set using the list's block style.

The unordered list marker can be set using any of the following block styles:

* square
* circle
* disc
* none or no-bullet (indented, but no bullet)
* unstyled (no indentation or bullet) (HTML only)

NOTE: These styles are supported by the default Asciidoctor stylesheet.

When present, the style name is assigned to the unordered list element as follows:

For HTML:: the style name is assigned to the `class` attribute on the `<ul>` element.

For DocBook:: the style name is assigned to the `mark` attribute on the `<itemizedlist>` element.

Here's an unordered list that has square bullets:

----
include::example$unordered.adoc[tag=square]
----

====
include::example$unordered.adoc[tag=square]
====
