= Unset Built-in Attributes

Document attributes can be unset in the document header and document body.

== Unset a document attribute in the header

Document attributes can be unset by adding a bang symbol (`!`) directly in front of or after the attribute's name.
Like when setting an attribute in a document header, the attribute entry must be on its own line.
Don't add a value to the entry.

[source]
----
= Title
:name!: <.>
:!name: <.>
----
<.> An attribute is unset when a `!` is appended to its name.
<.> An attribute is unset when a `!` is prefixed to its name.

Let's unset the attribute `example-caption`.
This is an attribute that is set and assigned a default value of `Example` automatically by Asciidoctor when you use an example block.

[source]
----
= Title
:!example-caption: <.>
----
<.> Example blocks won't be labeled and numbered, e.g., Example 1, because the attribute controlling that behavior is unset with the leading `!`.

== Unset a document attribute in the body

Some document attributes can be turned off in the body of the document using an attribute entry and the bang symbol (`!`) as described in the above section.
For example, if you set the section numbering attribute in the header of your document, but didn't want the two sections midway through the document to be numbered.
To do that, you'd unset `sectnums` before the first section you didn't want numbered and then reset it when you wanted numbering to start again.

[source]
----
= Title
:sectnums: <.>

== Section Title

:!sectnums: <.>
== Section Title

=== Section Title

:sectnums: <.>
== Section Title
----
<.> The `sectnums` attribute is set in the header to activate section numbering throughout the document.
<.> `sectnums` is unset by adding a `!` to it's name.
The `!` can be placed either before or after the attribute's name.
The attribute entry must be placed on its own line.
All of the sections below where the attribute is unset will not be numbered.
<.> `sectnums` is set and all subsequent sections will be numbered.
