= Footnotes

You can add footnotes to your document using the footnote macro (`+footnote:[text]+`).
If you specify a target (`+footnote:id[text]+`), you can refer to that footnote from multiple locations in the document. 
The target becomes the ID of the footnote, which you can use to refer to it (`+footnote:id[]+`).

.Footnote syntax
[source#ex-footnote]
----
include::example$footnote.adoc[tag=base-c]
----
<.> Insert the footnote macro directly after any punctuation.
Note that the footnote macro only uses a single colon (`:`).
<.> Insert the footnote's content within the square brackets (`+[]+`).
The text may span several lines.
<.> If you plan to reuse a footnote, specify a unique ID in the target position.
<.> To reference an existing footnote, you only need to specify the ID of the footnote in the target slot.
The text between the square brackets should be empty.
If both the ID and text are specified, and the ID has already been defined by an earlier footnote, the text is ignored.

The footnotes will be numbered consecutively throughout the article.

The results of <<ex-footnote>> are displayed below.

[.unstyled]
|===
a|
include::example$footnote.adoc[tag=base-x]
|===

== Externalizing a footnote

Since footnotes are defined using an inline macro, the footnote content must be inserted alongside the text it's annotating, making the text harder to read.
You can solve this problem by externalizing your footnotes using document attributes.
You can name the document attributes whatever you want, though a common practice is to name them with the `fn-` prefix.
The name of the attribute can be as verbose (`fn-disclaimer`) or concise (`fn-1`) as you prefer.

Here's the previous example with the footnotes defined in document attributes and inserted using attribute references.
Notice you still get the benefit of seeing where the footnote is placed without all the noise.

.Externalized footnote
[source]
----
include::example$footnote.adoc[tag=externalized]
----

This approach works since attribute references are expanded before footnotes are parsed.
Since the footnotes are now defined in the document header, they could be further externalized to an include file.

== Footnotes in Headings

If you use a footnote in a heading, you'll likely find that the footnote sequence is wrong.
That's because headings (section titles and discrete headings) get converted out of document order for the purpose of generating IDs and setting up cross references.

To resolve this problem, you must assign an explicit ID and reftext to any heading that contains a footnote.
For example:

[source]
----
See <<heading>>.

[[heading,Heading]]
== Headingfootnote:[This is a heading with a footnote]
----

Not only will this prevent the footnote from being processed out of document order (and thus assigned the wrong number in the sequence), it will also prevent the footnote number from reappearing in the text of an xref.
