= Insert Images from a URL

//(i.e., images with a URL target)
You can reference images served from any URL (e.g., your blog, an image hosting service, your server, etc.) and never have to worry about downloading the images and putting them somewhere locally.

== Image URL targets

Here are a few examples of images that have a URL target:

.Block image with a URL target
[source]
----
include::example$image.adoc[tag=url]
----

include::example$image.adoc[tag=url]

.Inline image with a URL target
[source]
----
include::example$image.adoc[tag=in-url]
----

include::example$image.adoc[tag=in-url]

NOTE: The value of `imagesdir` is ignored when the image target is a URL.

If you want to avoid typing the URL prefix for every image, and all the images are located on the same server, you can use the `imagesdir` attribute to set the base URL:

.Using a URL as the base URL for images
[source]
----
include::example$image.adoc[tag=base-url]
----

This time, `imagesdir` is used since the image target is not a URL (the value of `imagesdir` just happens to be one).

NOTE: This feature is included in the AsciiDoc compatibility file so that AsciiDoc.py gets it right, too.
