= Source Highlighting
:table-caption: Table

Source highlighting is applied to text that's assigned the `source` block style and a language.
You can define the source language directly on the block or globally using the `source-language` document attribute.

[#source-highlighter]
== source-highlighter attribute

Source highlighting isn't enabled by default.
To enable source highlighting, you must set the `source-highlighter` attribute in the document header using an attribute entry.

[source]
----
= Document Title
:source-highlighter: <value>
----

For example, here's how to enable syntax highlighting using Rouge:

[source]
----
= Document Title
:source-highlighter: rouge
----

You can also declare this attribute using the CLI or API.

[#available-source-highlighters]
== Available source highlighters

<<built-in-values>> lists the recognized values for the `source-highlighter` attribute and the toolchains that support the usage of the syntax highlighting libraries.

.Built-in source-highlighter values and the supporting toolchains
[#built-in-values%autowidth]
|===
|Library |Value |Toolchain

|CodeRay
|`coderay`
|Asciidoctor, AsciidoctorJ, Asciidoctor PDF

|highlight.js
|`highlight.js`
|Asciidoctor, AsciidoctorJ, Asciidoctor.js

|Pygments
|`pygments`
|Asciidoctor, Asciidoctor PDF

|Rouge
|`rouge`
|Asciidoctor, AsciidoctorJ, Asciidoctor PDF
|===

To use Rouge, CodeRay, or Pygments, you must have the appropriate library installed on your system.
See xref:asciidoctor:integrations:rouge.adoc[], xref:asciidoctor:integrations:coderay.adoc[], or xref:asciidoctor:integrations:pygments.adoc[] for installation instructions.

If you're using the client-side library xref:asciidoctor:integrations:highlightjs.adoc[], there's no need to install additional libraries.
The generated HTML will load the required source files from a CDN, custom URL, or file path.

.Source Highlighter vs. Syntax Highlighter
****
You might notice that the `source-highlighter` attribute uses the term "`source highlighter`", whereas the library that performs the highlighting is referred to as a "`syntax highlighter`".
What's the difference?

* The generally accepted term for a syntax (aka code) highlighter is "`syntax highlighter`".
* The syntax highlighter is applied to source blocks in AsciiDoc, hence why we say "`source highlighter`".

In other words, the `source-highlighter` attribute means "`use this syntax highlighter to colorize source blocks`".
****

== Apply source highlighting

To apply highlighting to source code, you must add the `source` style to a listing block, literal block, or paragraph and specify a source language.

.Source block with title and source highlighting
[listing#ex-code]
....
include::example$source.adoc[tag=src-base-co]
....
<.> Assign the block style `source` to the first position in the attribute list.
<.> An optional ID can be added to the block by appending it to style using the shorthand syntax (`#`) for `id`.
<.> Assign a source language to the second position.
<.> The source style is typically assigned to delimited listing blocks.

The result of <<ex-code>> is displayed below.

include::example$source.adoc[tag=src-base-co-res]

.Source style
[source#ex-style]
----
include::example$source.adoc[tag=src-para-co]
----
<.> Place the attribute list directly on the paragraph.
<.> Once an empty line is encountered the syntax highlighting is unset.

The result of <<ex-style>> is displayed below.

include::example$source.adoc[tag=src-para]

== Disable source highlighting

To disable source highlighting for a given source block, specify the language as `text` or remove the `source` style.

[#source-language]
== source-language attribute

If the majority of your source blocks use the same source language, you can set the `source-language` attribute in the document header and assign a language to it.

.Set source-language attribute
[listing#ex-language]
....
include::example$source.adoc[tag=src-lang]
....

You can override the global source language on an individual block by specifying a source language after `source`.

.Override source-language attribute
[listing#ex-override]
....
include::example$source.adoc[tag=override]
....
