= Quotes Substitutions
:navtitle: Quotes
:table-caption: Table
:y: Yes
//icon:check[role="green"]
:n: No
//icon:times[role="red"]

The replacement of the formatting markup on inline elements is called the quotes substitution step.

.Syntax input
[source#ex-quotes]
----
Happy werewolves are *really* slobbery.
----

For instance, when a document containing the markup in <<ex-quotes>> is converted to HTML, any asterisks enclosing text are replaced with `<strong>` HTML tags.
The resulting HTML can be seen in <<ex-html>> below.

.HTML output
[source#ex-html,html]
----
Happy werewolves are <strong>really</strong> slobbery.
----

<<table-quotes-html>> shows the HTML source code that is generated by the quotes substitution step.

.HTML source code generated from AsciiDoc formatting syntax
[#table-quotes-html%autowidth,cols=",^,^"]
|===
|Name |AsciiDoc |HTML

|emphasis
|+_word_+
|<em>word</em>

|strong
|+*word*+
|<strong>word</strong>

|monospace
|+`word`+
|<code>word</code>

|superscript
|+^word^+
|<sup>word</sup>

|subscript
|+~word~+
|<sub>word</sub>

|double curved quotes
|+"`word`"+
|+&#8220;word&#8221;+

|single curved quotes
|+'`word`'+
|+&#8216;word&#8217;+
|===

== Default quotes substitution

<<table-quotes>> lists the specific blocks and inline elements the quotes substitution step applies to automatically.

.Blocks and inline elements subject to the quotes substitution
[#table-quotes%autowidth,cols=",^"]
|===
|Blocks and elements |Substitution step applied by default

|Attribute entry values |{n}

|Comments |{n}

|Examples |{y}

|Literal, listings, and source |{n}

|Macros |{y} +
(except passthrough macros)

|Open |{y}

|Paragraphs |{y}

|Passthrough blocks |{n}

|Quotes and verses |{y}

|Sidebars |{y}

|Tables |Varies

|Titles |{y}
|===

[#quotes-value]
== quotes substitution value

The quotes substitution step can be modified on blocks and inline elements.
For blocks, the step's name, `quotes`, can be assigned to the xref:apply-subs-to-blocks.adoc[subs attribute].
For inline elements, the built-in values `q` or `quotes` can be applied to xref:apply-subs-to-text.adoc[inline text] to add the quotes substitution step.
