= Description Lists
:keywords: labeled list, definition list

// tag::label[]
A description list (often abbreviated as dlist) is useful when you need to include a description, definition, or supporting text for one or more terms.
Each item in a description list consists of a term or phrase followed by:

* one or more terms
* a separator following each term (typically a double colon, `::`)
* at least one space or endline
* the supporting content (i.e., description) (can be text, attached blocks, or both)

Here's an example of a description list that identifies parts of a computer:

[source]
----
include::example$description.adoc[tag=base]
----

By default, the content of each item is displayed below the label when rendered.
Here's a preview of how this list is rendered:

.A basic description list
====
include::example$description.adoc[tag=base]
====

If you want the label and content to appear on the same line, add the horizontal style to the list.

[source]
----
include::example$description.adoc[tag=base-horz]
----

====
include::example$description.adoc[tag=base-horz]
====

The content of a description list can be any AsciiDoc element.
For instance, we could rewrite the grocery list from above so that each aisle is a label rather than a parent outline list item.

[source]
----
include::example$description.adoc[tag=base-mix]
----

====
include::example$description.adoc[tag=base-mix]
====

Description lists are quite lenient about whitespace, so you can spread the items out and even indent the content if that makes it more readable for you:

[source]
----
include::example$description.adoc[tag=base-mix-alt]
----
// end::label[]

// tag::hybrid[]
[#three-hybrid]
Finally, you can mix and match the three list types within a single hybrid list.
Asciidoctor works hard to infer the relationships between the items that are most intuitive to us humans.

Here's a list that mixes description, ordered, and unordered list items:

[source]
----
include::example$description.adoc[tag=3-mix]
----

Here's how the list is rendered:

.A hybrid list
====
include::example$description.adoc[tag=3-mix]
====

You can include more xref:continuation.adoc[complex content in a list item] as well.
// end::hybrid[]
