= Character Replacement Attributes Reference
:page-aliases: character-replacement-reference.adoc

This page identifies built-in document attributes populated by the AsciiDoc processor that are geared towards character replacement.

This category of attributes provide portable replacements for common typographical marks (e.g., smart quotes and symbols) and non-visible characters (e.g., empty and no break space), an escaping mechanism for characters which have special meaning in AsciiDoc (e.g., plus and colon), and passthroughs for characters which get encoded by default (e.g., less than and greater than).
Like all document attributes, you can insert the value of any one of these attributes in your content using an xref:reference-attributes.adoc#reference-built-in[attribute reference] (e.g., `\{nbsp}`).

NOTE: The AsciiDoc processor does not prevent you from reassigning these predefined attributes.
However, you're encouraged to treat them as read-only.
Only a converter should override these attributes if the output format requires the use of a different encoding scheme.

.Built-in document attributes for character replacement
[%autowidth,cols="^~m,^~l,^~"]
|===
|Attribute name |Replacement text |Appearance

d|``blank``^[1]^
e|nothing
|{empty}

|empty
e|nothing
|{empty}

|sp
e|space
|{sp}

|nbsp
|&#160;
|{nbsp}

d|``zwsp``^[2]^
|&#8203;
|{zwsp}

d|``wj``^[3]^
|&#8288;
|{wj}

|apos
|&#39;
|{apos}

|quot
|&#34;
|{quot}

|lsquo
|&#8216;
|{lsquo}

|rsquo
|&#8217;
|{rsquo}

|ldquo
|&#8220;
|{ldquo}

|rdquo
|&#8221;
|{rdquo}

|deg
|&#176;
|{deg}

|plus
|&#43;
|{plus}

|brvbar
|&#166;
|&#166;

|vbar
|\|
|{vbar}

|amp
|&
|&

|lt
|<
|<

|gt
|>
|>

|startsb
|[
|[

|endsb
|]
|]

|caret
|^
|^

|asterisk
|*
|*

|tilde
|~
|~

|backslash
|\
|\

|backtick
|`
|`

|two-colons
|::
|::

|two-semicolons
|;;
|;;

|cpp
|C++
|C++

|pp
|&#43;&#43;
|&#43;&#43;
|===

^[1]^ An alias for the attribute `empty`, for those who find this terminology clearer.

^[2]^ The Zero Width Space (ZWSP) is a code point in Unicode that shows where a long word can be split if necessary.

^[3]^ The word joiner (WJ) is a code point in Unicode that prevents a line break at its position.

Notice that some replacement values are Unicode characters, whereas others are numeric character references (e.g., \&#34;).
The numeric character reference is when the Unicode character could interfere with the AsciiDoc syntax.
In this case, it's the responsibility of the converter to transform that numeric character reference into a format that is compatible with the output format.
For example, in the man page converter, each character reference is replaced with a troff macro.

Thus, the abstraction of using AsciiDoc attributes for character replacements not only gives the author control over how the document is interpreted, it also helps decouple content and presentation.
In other words, it's more portable to use an attribute reference in the content rather than hardcode a numeric character reference.
