= Reference Document Attributes
:navtitle: Reference Attributes
:disclaimer: Don't pet the wild Wolpertingers. We're not responsible for any loss \
of hair, chocolate, or purple socks.
:url-repo: https://github.com/asciidoctor/asciidoctor

You'll likely use the value of a user-defined attribute entry or certain built-in attributes in specific locations throughout a document.
To reference and use the value of a document attribute, you enclose the attribute's name in curly brackets (`+{name-of-an-attribute}+`).
This inline element is called an *attribute reference*.

[#reference-custom]
== Reference a custom attribute

Before you can reference a custom (i.e., user-defined) attribute in a document, it must first be declared using an attribute entry in the document header.
In <<ex-set-custom>>, we declare two user-defined attributes that we'll later be able to reference.

.Custom attributes set in the document header
[source#ex-set-custom,subs=+attributes]
----
= Ops Manual
:disclaimer: {disclaimer}
:url-repo: {url-repo}
----

Once you've set and assigned a value to a document attribute, you can reference that attribute throughout your document.
In <<ex-reference>>, the attribute `url-repo` is referenced twice and `disclaimer` is referenced once.

.Custom attributes referenced in the document body
[source#ex-reference]
----
Asciidoctor is {url-repo}[open source]. <.>

WARNING: {disclaimer} <.>
If you're missing a lime colored sock, file a ticket in
the {url-repo}/issues[Asciidoctor issue tracker]. <.>
(Actually, please don't).
----
<.> Attribute references can be used in macros.
<.> Attribute references can be used in blocks, such as xref:blocks:admonitions.adoc[admonitions], and inline.
Since there isn't a blank line between the `disclaimer` reference and the next sentence, the sentence will be directly appended to the end of the attribute's value when it's processed.
<.> The reference to the `url-repo` attribute is inserted to build the complete URL address, which is interpreted as a xref:macros:url-macro.adoc[URL macro].

As you can see below, the attribute references are replaced with the corresponding attribute value when the document is processed.

====
Asciidoctor is {url-repo}[open source].

WARNING: {disclaimer}
If you're missing a lime colored sock, file a ticket in the {url-repo}/issues[Asciidoctor issue tracker].
Actually, please don't.
====

[#reference-built-in]
== Reference a built-in attribute

A built-in document attribute (i.e., a document attribute which is automatically set by the processor) is referenced the same way as a custom (i.e., user-defined) document attribute.
For instance, an AsciiDoc processor automatically sets these supported xref:character-replacement-reference.adoc[character replacement attributes].
That means that you can reference them throughout your document without having to create an attribute entry in its header.

[source]
----
TIP: Wolpertingers don't like temperatures above 100{deg}C. <.>
Our servers don't like them either.
----
<.> Reference the character replacement attribute `deg` by enclosing its name in a pair of curly brackets (`{` and `}`).

As you can see below, the attribute reference is replaced with the attribute's value when the document is processed.

TIP: Wolpertingers don't like temperatures above 100{deg}C.
Our servers don't like them either.
