////
.Description list
[source]
----
CPU:: <1>
The brain of the computer. <2>
<3>
Hard drive::
Permanent storage for operating system and/or user files.
----
<1> Follow each term with two colons.
<2> Enter the definition text on a new line below the term.
<3> Enter a single blank line between each term/definition pair.

////

// tag::base[]
CPU:: The brain of the computer.
Hard drive:: Permanent storage for operating system and/or user files.
RAM:: Temporarily stores information the CPU uses during operation.
Keyboard:: Used to enter text or control items on the screen.
Mouse:: Used to point to and select items on your computer screen.
Monitor:: Displays information in visual form using text and graphics.
// end::base[]

// tag::base-horz[]
[horizontal]
CPU:: The brain of the computer.
Hard drive:: Permanent storage for operating system and/or user files.
RAM:: Temporarily stores information the CPU uses during operation.
// end::base-horz[]

// tag::qr-base[]
First term:: The description can be placed on the same line
as the term.
Second term::
Description of the second term.
The description can also start on its own line.
// end::qr-base[]

// tag::base-mix[]
Dairy::
* Milk
* Eggs
Bakery::
* Bread
Produce::
* Bananas
// end::base-mix[]

// tag::base-mix-alt[]
Dairy::

  * Milk
  * Eggs

Bakery::

  * Bread

Produce::

  * Bananas
// end::base-mix-alt[]

// tag::3-mix[]
Operating Systems::
  Linux:::
    . Fedora
      * Desktop
    . Ubuntu
      * Desktop
      * Server
  BSD:::
    . FreeBSD
    . NetBSD

Cloud Providers::
  PaaS:::
    . OpenShift
    . CloudBees
  IaaS:::
    . Amazon EC2
    . Rackspace
// end::3-mix[]

// tag::qa[]
[qanda]
What is the answer?::
This is the answer.

Have you seen my duck?:: No.
// end::qa[]
