= Line and Page Breaks

== Line breaks

Since adjacent lines of text are combined into a single paragraph when Asciidoctor converts a document, that means you can wrap paragraph text or put each sentence or phrase on a separate line.
The line breaks won't appear in the output.

However, if you want the line breaks in a paragraph to be preserved, you can either use a space followed by a plus sign (`{plus}`) or set the `hardbreaks` option on the paragraph.
This results in a visible line break (e.g., `<br>`) following each line.

.Line breaks preserved using a space followed by the plus sign ({plus})
[source#ex-plus]
----
include::example$paragraph.adoc[tag=hb]
----

The result of <<ex-plus>> is displayed below.

====
include::example$paragraph.adoc[tag=hb]
====

.Line breaks preserved using the hardbreaks option
[source#ex-option]
----
include::example$paragraph.adoc[tag=hb-p]
----

The result of <<ex-option>> is displayed below.

====
include::example$paragraph.adoc[tag=hb-p]
====

To preserve line breaks throughout your whole document, set the `hardbreaks` attribute in the document header.

.Line breaks preserved throughout the document using the hardbreaks attribute
[source#ex-attribute]
----
include::example$paragraph.adoc[tag=hb-attr]
----

You can also preserve line breaks using xref:verbatim:literal.adoc[literal blocks], xref:verbatim:listing.adoc[listing blocks], and xref:verse.adoc[verses].

== Page breaks

.Page break syntax
[source#ex-page-break]
----
<<<
----
