= Callouts

Callout numbers (aka callouts) provide a means to add annotations to lines in a verbatim block.

== Callout syntax

Each callout number used in a verbatim block must appear twice.
The first use, which goes within the verbatim block, marks the line being annotated (i.e., the target).
The second use, which goes below the verbatim block, defines the annotation text.
Multiple callout numbers may be used on a single line.

IMPORTANT: The callout number (at the target) must be placed at the end of the line.

Here's a basic example of a verbatim block that uses callouts:

.Callout syntax
[source#ex-basic,subs=-callouts]
....
include::example$callout.adoc[tag=basic]
....

The result of <<ex-basic>> is rendered below.

include::example$callout.adoc[tag=basic]

Since callout number can interfere with the syntax of the code they are annotating, Asciidoctor provides several features to hide the callout numbers from both the source and the converted document.
The sections that follow detail these features.

== Copy and paste friendly callouts

In versions prior to Asciidoctor 0.1.4, when a reader visiting an HTML page generated by Asciidoctor selected source code from a listing that contained callouts and copied it, the callout numbers would get caught up in the copied text.
If the reader pasted that code and tried to run it, likely the extra characters from the callouts would cause compile or runtime errors.

Asciidoctor uses CSS to prevent callouts from being selected.

On the other side of the coin, you don't want the callout annotations or CSS messing up your raw source code either.
You can tuck your callouts neatly behind line comments.
Asciidoctor will recognize the line comments characters in front of a callout number, optionally offset by a space, and remove them when converting the document.

Here are the line comments that are supported:

.Prevent callout copy and paste
[source#ex-prevent,subs=specialcharacters]
....
include::example$callout.adoc[tag=b-nonselect]
....

The result of <<ex-prevent>> is rendered below.

// The listing style must be added above the rendered block so it is rendered correctly because we're setting `source-language` in the component descriptor which automatically promotes unstyled listing blocks to source blocks.
[listing]
include::example$callout.adoc[tag=b-nonselect]

=== Custom line comment prefix

An AsciiDoc processor recognizes the most ubiquitous line comment prefixes as a convenience.
If the source language you're embedding does not support one of these line comment prefixes, you can customize the prefix using the `line-comment` attribute on the block.

Let's say we want to tuck a callout behind a line comment in erlang code.
In this case, we would set the `line-comment` character to `%`, as shown in this example:

.Customize the line comment prefix
[source#ex-line-comment,subs=-callouts]
....
include::example$callout.adoc[tag=line-comment]
....

The result of <<ex-line-comment>> is rendered below.

// The listing style must be added above the rendered block so it is rendered correctly because we're setting `source-language` in the component descriptor which automatically promotes unstyled listing blocks to source blocks.
[listing]
include::example$callout.adoc[tag=line-comment]

Even though it's not specified in the attribute, one space is still permitted immediately following the line comment prefix.

=== XML callouts

XML doesn't have line comments, so our "`tuck the callout behind a line comment`" trick doesn't work here.
To use callouts in XML, you must place the callout's angled brackets around the XML comment and callout number.

Here's how it appears in a listing:

.XML callout syntax
[source#ex-xml,subs=specialcharacters]
....
include::example$callout.adoc[tag=source-xml]
....

The result of <<ex-xml>> is rendered below.

include::example$callout.adoc[tag=source-xml]

Notice the comment has been replaced with a circled number that cannot be selected (if not using font icons it will be
rendered differently and selectable).
Now both you and the reader can copy and paste XML source code containing callouts without worrying about errors.

== Callout icons

The font icons setting also enables callout icons drawn using CSS.

----
include::example$callout.adoc[tag=co-icon]
----
<.> Activates the font-based icons in the HTML5 backend.
<.> Admonition block that uses a font-based icon.
