// tag::para-c[]
WARNING: Wolpertingers are known to nest in server racks. <.> <.>
Enter at your own risk.
// end::para-c[]

// tag::para[]
WARNING: Wolpertingers are known to nest in server racks.
Enter at your own risk.
// end::para[]

// tag::bl[]
[IMPORTANT]
.Feeding the Werewolves
====
While werewolves are hardy community members, keep in mind the following dietary concerns:

. They are allergic to cinnamon.
. More than two glasses of orange juice in 24 hours makes them howl in harmony with alarms and sirens.
. Celery makes them sad.
====
// end::bl[]

// tag::bl-c[]
[IMPORTANT] <.>
.Feeding the Werewolves
==== <.>
While werewolves are hardy community members, keep in mind the following dietary concerns:

. They are allergic to cinnamon.
. More than two glasses of orange juice in 24 hours makes them howl in harmony with alarms and sirens.
. Celery makes them sad.
====
// end::bl-c[]

// tag::bl-nest[]
[IMPORTANT]
.Feeding the Werewolves
======
While werewolves are hardy community members, keep in mind the following dietary concerns:

. They are allergic to cinnamon.
. More than two glasses of orange juice in 24 hours makes them howl in harmony with alarms and sirens.
. Celery makes them sad.
======
// end::bl-nest[]

// in qr
// tag::b-para[]
NOTE: An admonition draws attention to auxiliary information.

Here are the other built-in admonition types:

TIP: Pro tip...

IMPORTANT: Don't forget...

WARNING: Watch out for...

CAUTION: Ensure that...
// end::b-para[]

// in qr
// tag::b-bl[]
[NOTE]
====
An admonition block may contain complex content.

.A list
- one
- two
- three

Another paragraph.
====
// end::b-bl[]
