// tag::para-c[]
WARNING: Wolpertingers are known to nest in server racks. <.> <.>
Enter at your own risk.
// end::para-c[]

// tag::para[]
WARNING: Wolpertingers are known to nest in server racks.
Enter at your own risk.
// end::para[]

// tag::bl[]
[IMPORTANT]
.Feeding the Werewolves
====
While werewolves are hardy community members, keep in mind the following dietary concerns:

. They are allergic to cinnamon.
. More than two glasses of orange juice in 24 hours makes them howl in harmony with alarms and sirens.
. Celery makes them sad.
====
// end::bl[]

// tag::bl-c[]
[IMPORTANT] <.>
.Feeding the Werewolves
==== <.>
While werewolves are hardy community members, keep in mind the following dietary concerns:

. They are allergic to cinnamon.
. More than two glasses of orange juice in 24 hours makes them howl in harmony with alarms and sirens.
. Celery makes them sad.
====
// end::bl-c[]

// tag::bl-nest[]
[IMPORTANT]
.Feeding the Werewolves
======
While werewolves are hardy community members, keep in mind the following dietary concerns:

. They are allergic to cinnamon.
. More than two glasses of orange juice in 24 hours makes them howl in harmony with alarms and sirens.
. Celery makes them sad.
======
// end::bl-nest[]

// tag::b-para[]
NOTE: An admonition draws the reader's attention to auxiliary information.

Here are the other built-in admonition types:

IMPORTANT: Don't forget the children!

TIP: Look for the warp zone under the bridge.

CAUTION: Slippery when wet.

WARNING: The software you're about to use is untested.

IMPORTANT: Sign off before stepping away from your computer.
// end::b-para[]

// tag::b-bl[]
[NOTE]
====
An admonition block may contain complex content.

.A list
- one
- two
- three

Another paragraph.
====
// end::b-bl[]
