= Book Parts

Parts can only be used when the document type is `book`.
The presence of at least one part implies that the document is a multi-part book.
(There's no dedicated `doctype` for a multi-part book to distinguish it from a book with only chapters).

== Anatomy of a part

A part is a level 0 section.
A part must contain at least one level 1 section.
The first part is the first level 0 section in the document that comes after the document title.
Like the document title, a part is designated by a level 0 section title (`=`).

[source]
----
include::example$part.adoc[tag=basic]

...
----

A part can have an optional introduction (similar to the preamble of the document), known as a part intro.
The part intro is the content between the part title and the first section in the part.
The part intro can be marked explicitly using the `partintro` style on either a paragraph or open block.

AsciiDoc provides document attributes to control the xref:part-numbers-and-labels.adoc[numbering and labeling parts].

== Part intro

The content between the part title and the first section in the part is the part intro.
Normally, the part intro is inferred, as shown here:

[source]
-----
include::example$part.adoc[tags=**;!style]
-----

You can mark the part intro explicitly by adding the `partintro` style on the sole block before the first section.

[source]
-----
include::example$part.adoc[tags=**]
-----

== Special sections for parts

A part can have its own xref:preface.adoc[preface], xref:bibliography.adoc[bibliography], xref:glossary.adoc[glossary] and xref:user-index.adoc[index].

[source]
----
include::example$multi-special.adoc[tag=part]
----
